### ISSUE TITLE
Link quebrado

### ISSUE THREAD

**Issue by JoiaribeAlves** [leandrucarvalho/barber-landing-page#13]
O link na seção 'about' continua quebrado.

![Screenshot from 2024-06-14 22-17-59](https://github.com/leandrucarvalho/barber-landing-page/assets/102931920/99f7cfd8-12b8-4762-8ba7-bc53880889a8)

**Comment by leandrucarvalho** [comment]
Entendi, não sabia que era no 'about'. Obrigado por reportar, atualizei la.
